blog_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    re_path(r'^post/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new',views.CreatePostView.as_view(),name='post_new'),
    re_path(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(), name='post_update'),
    re_path(r'^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts', views.DraftListView.as_view(), name='post_draft_list'),
    re_path(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post, name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve, name='comment_approve'),
    re_path(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove, name='comment_remove'),
    re_path(r'^post/(?P<pk>\d+)/publish/$',views.post_publish, name='post_publish')
]

my_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
    path('accounts/login/',views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

blog_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_app:post_detail", kwargs={'pk': self.pk})

class Comment(models.Model):
    post = models.ForeignKey(
        'blog_app.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("blog_app:post_list", kwargs={'pk': self.pk})

blog_app/forms.py
from django import forms
from blog_app.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

blog_app/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import (ListView, DetailView,
    CreateView, TemplateView, UpdateView, DeleteView)
from blog_app.models import Post, Comment
from blog_app.forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
class AboutView(TemplateView):
    template_name = "about.html"
    
class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post
    # Need to change the template_name because of change in settings.py file

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog_app:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

#####################################################

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog_app:post_detail',pk=pk)

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog_app:post_detail',pk=post.pk)
    else:
    # Has not filled the Comment Form
        form = CommentForm()
    return render(request,'blog_app/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('blog_app:post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog_app:post_detail', pk=post_pk)

blog_app/templates/blog_app/about.html
{% extends 'blog_app/base.html' %}

{% block content %}
    <h1>About Me</h1>
    <p>Thanks for checking it out</p>
{% endblock %}

blog_app/templates/blog_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog App</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css"
        media="screen" charset="utf-8">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One&display=swap" rel="stylesheet">    
</head>
<body class="loader">
    <nav class="navbar navbar-default techfont custom-navbar">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand bigbrand" href="{% url 'blog_app:post_list' %}">My Blog</a></li>
                <li><a href="{% url 'blog_app:about' %}">About</a></li>
                <li><a href="https://github.com">GitHub</a></li>
                <li><a href="https://linkedin.com">LinkedIn</a></li>
            </ul >

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'blog_app:post_new' %}">New Post</a>
                    </li>
                    <li>
                        <a href="{% url 'blog_app:post_draft_list' %}">Drafts</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Log Out</a>
                    </li>
                    <li>
                        <a>Welcome: {{ user.username }}</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav navbar-right" href="{% url 'login' %}">
                            <span class="glyphicon glyphicon-user"></span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- CONTENT BLOCK  -->
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="blog_posts">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

</body>
</html>

blog_app/templates/blog_app/blog_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/dd3f00a30e.js" crossorigin="anonymous"></script>
    <title>Blog App</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand mb-0 h1" href="#">My Tech Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link mb-0 h5" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mb-0 h5" href="#">Github</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mb-0 h5" href="#">LinkedIn</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}"><i class="fas fa-user-alt fa-lg"></i></a>
                </li>
            </ul>
        </div>
    </nav>

    {% block body_block %}
    {% endblock %}
</body>
</html>

blog_app/templates/blog_app/comment_form.html
{% extends 'blog_app/base.html' %}

{% block content %}
    <h1>New Comment</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="save btn btn-default" type="submit">Post Comment</button>
    
        <script>
            var editor = new MediumEditor('.editable');
        </script>
    
    </form>
{% endblock %}

blog_app/templates/blog_app/post_confirm_delete.html
{% extends 'blog_app/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" class="btn btn-danger" value="confirm">
    </form>
{% endblock %}

blog_app/templates/blog_app/post_detail.html
{% extends 'blog_app/base.html' %}

{% block content %}
    <h1 class="posttitle loader">{{post.title}}</h1>
    {% if post.published_date %}
        <div class="date postdate">
            {{post.published_date}}
        </div>
    {% else %}
        <a class="btn btn-default" href="{% url 'blog_app:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}
    <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'blog_app:post_update' pk=post.pk %}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <a class="btn btn-primary" href="{% url 'blog_app:post_remove' pk=post.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
        </a>
    {% endif %}
        
    <hr>

    <a class="btn btn-primary btn-comment" href="{% url 'blog_app:add_comment_to_post' pk=post.pk %}">
        Add Comment
    </a>

    <!-- List of comments -->
    <div class="container">
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog_app:comment_remove' pk=comment.pk %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a class="btn btn-primary" href="{% url 'blog_app:comment_approve' pk=comment.pk %}">
                        <span class="glyphicon glyphicon-ok"></span>
                    </a>
                {% endif %}
                <p>{{ comment.text|safe|linebreaks }}</p>
                <p>Posted By: {{ comment.author }}</p>
            {% endif %}

        {% empty %}
        <p>No comments!</p>
        {% endfor %}
    </div>

{% endblock %}

blog_app/templates/blog_app/post_draft_list.html
{% extends 'blog_app/base.html' %}
{% block content %}
    {% for post in posts %}
        <div class="Post">
            <p class="date">Created: {{ post.created_date|date: 'd-m-Y' }}</p>
            <h1><a href="{% url 'blog_app:post_detail' pk=post.pk">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}

{% endblock %}

blog_app/templates/blog_app/post_form.html
{% extends 'blog_app/base.html' %}
{% block content %}
    <h1>New Post</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="save btn btn-default" type="submit">Save</button>

        <script>
            var editor = new MediumEditor('.editable');
        </script>

    </form>
{% endblock %}

blog_app/templates/blog_app/post_list.html
{% extends 'blog_app/base.html' %}

{% block content %}
<div class="centerstage">
    {% for post in post_list %}
        <div class="post">
            <h1><a href="{%url 'blog_app:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <div class="date">
                <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
            </div>
        </div>
        <a href="{% url 'blog_app:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
    {% endfor %}    

</div>
{% endblock %}